#!/bin/bash
source /usr/lib/openfoam/openfoam2112/etc/bashrc
export OMPI_MCA_btl_vader_single_copy_mechanism=none

cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

# Alternative decomposeParDict name:
decompDict="-decomposeParDict system/decomposeParDict.6"
## Standard decomposeParDict name:
# unset decompDict

date
echo "***Feature Extraction***"
runApplication surfaceFeatureExtract

echo "***Block meshing ***"
runApplication blockMesh

echo "***Decomposing  Subdomains  ***"
runApplication $decompDict decomposePar


echo "***Parallel Meshing   ***"
runParallel $decompDict snappyHexMesh -overwrite



touch a.foam
echo "---Mesh Size---"
grep "Layer mesh :" log.snappyHexMesh
echo "--- CPU Timings---"
grep "Finished Meshing" log.snappyHexMesh
date
echo "****** ALL DONE ******"
#------------------------------------------------------------------------------
